config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# Article model
class Article < ApplicationRecord
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles, dependent: :destroy
  has_secure_password

  validates :username, presence: true,
                       uniqueness: { case_sensitive: false },
                       length: { minimum: 3, maximum: 25 }

  validates :email, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 105 },
                    format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    redirect_to login_path, alert: 'You must be logged in to perform this action.' unless logged_in?
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# Controller for Article model.
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[update edit destroy]

  def show; end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 6)
  end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article      = Article.new article_params
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully!'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update article_params
      flash[:notice] = 'Article was updated successfully!'
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find params[:id]
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    redirect_to @article, alert: 'Action not allowed' unless current_user == @article.user || current_user.admin?
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# Category Controller
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :require_admin_user, except: %i[index show]

  def new
    @category = Category.new
  end

  def show
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end

  def create
    @category = Category.new category_params

    if @category.save
      redirect_to @category, notice: 'Category created successfully!'
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @category.update category_params
      redirect_to @category, notice: 'Category updated successfully!'
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 18)
  end

  def destroy
    redirect_to categories_path if @category.destroy
  end

  private

  def set_category
    @category = Category.find params[:id]
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin_user
    unless logged_in? && current_user.admin?
      redirect_to categories_path,
                  alert: 'Only admin users can perform this action.'
    end
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

# SessionsController
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by username: params[:session][:username].downcase

    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user, notice: "Welcome, #{user.username}!"
    else
      flash.now[:alert] = 'Invalid credentials!'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'See you soon!'
  end
end

app/controllers/users_controller.rb
# Users Controller
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  before_action :require_user, only: %i[edit update destroy]
  before_action :require_same_user, only: %i[edit update destroy]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog, #{@user.username}!"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:notice] = 'Account details updated successfully!'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if current_user == @user
    redirect_to root_path, notice: 'Account deleted! We are sad to see you go! :('
  end

  private

  def set_user
    @user = User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def require_same_user
    redirect_to @user, alert: 'Action not allowed' unless current_user == @user || current_user.admin?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to articles_path if logged_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<div class="card h-100 p-3">
  <div class="card-body">
    <h2 class="card-title"><%= link_to article.title, article_path(article), class: "text-decoration-none text-reset" %></h2>
    <h6 class="card-subtitle mb-2 text-muted">Created
      by <%= article.user ? article.user.username : 'anonymous' %>
      , <%= time_ago_in_words article.created_at %> ago.</h6>
    <div class="my-2">
      <% if article.categories.any? %>
        <%= render article.categories %>
      <% end %>
    </div>
    <p class="card-text"><%= truncate(article.description, length: 200) %></p>
    <div>
      <%= link_to 'Show', article_path(article), class: "btn btn-outline-dark card-link" %>
      <% if current_user == article.user || current_user.admin? %>
        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-secondary card-link" %>
        <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger card-link" %>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<%= form_with model: @article, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :title, class: "form-label" %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :description, class: "form-label" %>
    <%= f.text_area :description, rows: 10, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= f.label :categories, class: "form-label" %>
    <%= f.collection_select :category_ids, Category.all, :id, :name, { prompt: 'Select zero or more categories' }, { multiple: true, class: "form-select", size: 6 } %>
  </div>

  <div class="">
    <%= f.submit class: "btn btn-success btn" %>
    <%= link_to 'Back', articles_path, class: "btn btn btn-light mx-3" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-9 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">Edit Article: <%= @article.id %></h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="d-flex flex-row justify-content-between align-items-center">
  <h1>Articles</h1>
  <% if logged_in? %>
    <%= link_to 'New Article', new_article_path, class: "btn btn-dark btn-lg text-decoration-none text-white" %>
  <% end %>
</div>

<div class="container-fluid p-0 mt-3">
  <%= will_paginate @articles, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <div class="row row-cols-1 row-cols-sm-1 row-cols-md-3 g-3">
    <% @articles.each do |article| %>
      <div class="col">
        <div class="card text-white bg-dark h-100 p-3">
          <div class="card-body">
            <h2 class="card-title"><%= link_to article.title, article_path(article), class: "text-decoration-none text-white" %></h2>
            <h6 class="card-subtitle mb-2 text-muted">Created
              by <%= article.user ? link_to(article.user.username, user_path(article.user), class: 'text-muted') : 'anonymous' %>
              , <%= time_ago_in_words article.created_at %> ago.</h6>
            <div class="my-2">
              <% if article.categories.any? %>
               <%= render article.categories %>
              <% end %>
            </div>
            <p class="card-text"><%= truncate(article.description, length: 200) %></p>
            <div>
              <%= link_to 'Show', article_path(article), class: "btn btn-outline-light card-link" %>
              <% if logged_in? && (current_user == article.user || current_user.admin?)%>
                <%= link_to 'Edit', edit_article_path(article), class: "btn btn-outline-secondary card-link" %>
                <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger card-link" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="my-3">
    <%= will_paginate @articles, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-9 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">New article</h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-9">
    <div class="h-100 p-4 bg-light rounded-3">
      <h1 class="mb-0"><%= @article.title %></h1>
      <h6 class="mb-3 text-muted">Created
        by <%= @article.user ? link_to(@article.user.username, user_path(@article.user), class: 'text-muted') : 'anonymous' %>
        , <%= time_ago_in_words @article.created_at %> ago.</h6>
      <div>
        <% if @article.categories.any? %>
          <%= render @article.categories %>
        <% end %>
      </div>
      <p><%= simple_format @article.description %></p>

      <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
        <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-secondary" %>
        <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
      <% end %>
      <%= link_to 'Back', articles_path, class: "btn btn-light" %>
    </div>
  </div>
</div>

app/views/categories/_category.html.erb
<span class="badge bg-info text-dark me-1"><%= link_to category.name, category_path(category), class: 'text-decoration-none text-dark' %></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
<%= form_with model: @category, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: "form-label" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="">
    <%= f.submit class: "btn btn-success btn" %>
    <%= link_to 'Back', categories_path, class: "btn btn btn-light mx-3" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-6 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">Edit category</h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/index.html.erb
<div class="d-flex flex-row justify-content-between align-items-center">
  <h1>Categories</h1>
  <% if logged_in? && current_user.admin? %>
    <%= link_to 'New Category', new_category_path, class: "btn btn-dark btn-lg text-decoration-none text-white" %>
  <% end %>
</div>

<div class="container-fluid p-0 mt-3">
  <%= will_paginate @categories, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <div class="row row-cols-1 row-cols-sm-1 row-cols-md-3 g-3">
    <% @categories.each do |category| %>
      <div class="col">
        <div class="card">
          <div class="card-body d-flex justify-content-between align-items-center">
            <h4 class="mb-0"><%= link_to category.name, category_path(category), class: 'text-decoration-none text-dark' %>
            </h4>
            <h5 class="mb-0">
              <span class="badge bg-secondary"><%= pluralize(category.articles.count, 'article') %></span>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="my-3">
    <%= will_paginate @articles, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-6 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">New category</h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-9">
    <div class="card">
      <div class="card-body d-flex align-items-center">
        <h1 class="mb-0"><%= @category.name %></h1>
        <% if current_user.admin? %>
          <div class="ms-3">
            <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-secondary card-link" %>
            <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger card-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-md-9">
    <div class="card border-dark mb-4">
      <div class="card-header bg-dark">
        <h3 class="text-white mb-0">Articles</h3>
      </div>
      <div class="card-body">
        <div class="row g-3">
          <% if @articles.any? %>
            <%= will_paginate @articles, list_classes: %w[pagination], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            <% @articles.each do |article| %>
              <div class="col-12">
                <%= render 'articles/article', article: article %>
              </div>
            <% end %>
          <% else %>
            <p class="text-center text-muted">No articles found</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <p><%= msg %></p>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container py-2">
    <%= link_to 'Alpha Blog', root_path, class: 'navbar-brand mb-0 h1 fw-bold fs-3' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Create article", new_article_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="navbar-nav d-flex me-3">
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="user" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Hi, <strong><%= current_user.username %> </strong>
            </a>
            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="user">
              <% if current_user.admin? %>
                <li><p class="dropdown-header text-danger">You are Admin</p></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
              <% end %>
              <li><%= link_to "Go to profile", user_path(current_user.id), class: "dropdown-item" %></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %></li>
            </ul>
          </li>
        <% else %>
          <div class="nav-item">
            <%= link_to "Sign Up", signup_path, class: "nav-link" %>
          </div>
          <div class="nav-item">
            <%= link_to "Log in", login_path, class: "nav-link" %>
          </div>
        <% end %>
      </div>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>AlphaBlog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <!--  Favicon Images - Start-->
  <%= favicon_link_tag 'favicon.svg', type: "image/svg+xml" %>
  <!--  Favicon Images - Start-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body>
<%= render 'layouts/navbar' %>
<div class="min-vh-100 position-relative">
  <div class="container pt-3 pb-5">

    <%= render 'layouts/messages' %>
    <div class="pb-5">
      <%= yield %>
    </div>
  </div>
  <%= render 'shared/footer' %>
</div>

</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <h4 class="alert-heading">Some errors were encountered:</h4>
    <ul>
      <% obj.errors.full_messages.each do |err| %>
        <li><%= err %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3 bg-dark position-absolute bottom-0 min-vw-100">
  <div class="container text-center">
    <span class="text-white-50">Copyright &copy; Alpha Blog, 2022</span>
  </div>
</footer>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<%= form_with model: @user, local: true do |f| %>
  <div class="mb-3">
    <%= f.label :username, class: "form-label" %>
    <%= f.text_field :username, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :email, class: "form-label" %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :password, class: "form-label" %>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="">
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-success btn") %>
    <%= link_to 'Back', articles_path, class: "btn btn btn-light mx-3"%>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="card mb-3">
  <div class="row g-0">
    <div class="col-md-3">
      <%= image_tag asset_path("profile_pic.jpg", type: :images), alt: "Profile pic", class: "img-fluid rounded-start", :style => "height: 200px" %>
    </div>
    <div class="col-md-9">
      <div class="card-body h-100">
        <h2 class="card-title"><%= user.username %></h2>
        <h6 class="card-subtitle mb-2 text-muted"><%= user.email %> - Joined <%= time_ago_in_words(user.created_at) %>
          ago</h6>
        <p class="card-text">Wrote <strong><%= pluralize(user.articles.count, 'article') %></strong></p>
        <div class="mt-5">
          <% if !@users && (logged_in? && current_user == user || current_user.admin?) %>
            <%= link_to 'Edit profile', edit_user_path(user), class: "btn btn-outline-info card-link" %>
            <%= link_to 'Delete account', user_path(user), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger card-link" %>
          <% end %>
          <% if @users %>
            <%= link_to 'Visit profile', user_path(user), class: "btn btn-outline-success card-link" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-6 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">Edit</h1>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="row justify-content-center mb-3">
  <div class="col">
    <h1>Bloggers</h1>
  </div>
</div>
<div class="row">
  <%= will_paginate @users, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  <% @users.each do |user| %>
    <div class="col-xl-6">
      <%= render 'user', user: user %>
    </div>
  <% end %>
  <%= will_paginate @users, list_classes: %w[pagination justify-content-center], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
</div>

app/views/users/new.html.erb
<div class="row justify-content-center my-4">
  <div class="col-md-6 col-sm-12">
    <div class="card border-dark">
      <div class="card-header bg-dark">
        <h1 class="text-white mb-0">Sign Up</h1>
      </div>
      <div class="card-body">
          <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row justify-content-center">
  <div class="col-md-9">
    <%= render 'user', user: @user %>
  </div>
</div>
<div class="row justify-content-center">
  <div class="col-md-9">
    <div class="card border-dark mb-4">
      <div class="card-header bg-dark">
        <h3 class="text-white mb-0">Articles</h3>
      </div>
      <div class="card-body">
        <div class="row g-3">
          <% if @articles.any? %>
            <%= will_paginate @articles, list_classes: %w[pagination], renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
            <% @articles.each do |article| %>
              <div class="col-12">
                <%= render 'articles/article', article: article %>
              </div>
            <% end %>
          <% else %>
            <p class="text-center text-muted">No articles found</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="mt-4 p-5 mb-4 text-white bg-dark rounded-3">
  <div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">Alpha Blog</h1>
    <p class="col-md-8 fs-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet cupiditate error in placeat
      quia, ullam vero! Accusantium delectus deserunt, eius, error facere maiores maxime molestiae non qui, quibusdam
      similique vel.</p>
    <%= link_to 'Sign Up!', signup_path, class: 'btn btn-outline-light btn-lg' %>
  </div>
</div>
<div class="row align-items-md-stretch g-4">
  <div class="col-md-6">
    <div class="h-100 p-5 bg-light rounded-3">
      <h2>Search your favourite article</h2>
      <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and
        match with additional component themes and more.</p>
      <button class="btn btn-outline-dark" type="button">Learn more...</button>
    </div>
  </div>
  <div class="col-md-6">
    <div class="h-100 p-5 bg-light border rounded-3">
      <h2>Enhance better content</h2>
      <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look
        under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for
        equal-height.</p>
      <button class="btn btn-outline-secondary" type="button">Add review</button>
    </div>
  </div>
</div>